env: "dev"
db:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "2004"
  dbname: "T_invest_DB"
  sslmode: "disable"
http_server:
  addres: "localhost:8082"
  timeout: 4s
  iddle_timeout: 60s